x-def-logging: &default-logging
  logging:
    driver: "loki"
    options:
      loki-url: "http://loki:3100/loki/api/v1/push"
      loki-batch-size: "100"
      loki-retries: "2"
      loki-max-backoff: "1000ms"
      loki-timeout: "1s"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    <<: *default-logging
    environment:
      SERVER_IP: ${SERVER_IP:-localhost}
      APP_PORT: ${APP_PORT}
      APP_DSN: ${APP_DSN}
      APP_MIGRATIONS: ${APP_MIGRATIONS}
      APP_ENV: ${APP_ENV}
      APP_SECRET: ${APP_SECRET}
      VERSION: ${VERSION}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - logging

  db:
    image: postgres:latest
    restart: always
    <<: *default-logging
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
    networks:
      - logging

  loki:
    hostname: loki
    image: grafana/loki:2.9.0
    volumes:
      - ./grafana/loki/retention-config.yaml:/etc/grafana/loki/retention-config.yaml
      - loki-data:/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/grafana/loki/retention-config.yaml
    networks:
      - logging

  grafana:
    hostname: grafana
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - logging

volumes:
  pg-data:
  grafana-data:
  loki-data:

networks:
  logging:
    driver: bridge
