name: CI Watchlist

on:
  push:
    branches:
      - ci/cd
  pull_request:
    branches:
      - ci/cd

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10-dind
        options: --privileged

    env:
      APP_PORT: ${{ secrets.APP_PORT }}
      APP_SECRET: ${{ secrets.APP_SECRET }}
      APP_ENV: ${{ secrets.APP_ENV }}
      APP_MIGRATIONS: ${{ secrets.APP_MIGRATIONS }}
      APP_DSN: ${{ secrets.APP_DSN }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASS: ${{ secrets.POSTGRES_PASS }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}

    steps:
      - name: Print environment variables
        run: |
          echo "APP_PORT=${{ secrets.APP_PORT }}"
          echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep 'tag_name' | cut -d\" -f4)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Build Docker images
        run: docker-compose -f docker-compose.yml build --no-cache

      - name: Run Docker Compose
        run: docker-compose -f docker-compose.yml up -d