name: CI Watchlist

on:
  push:
    branches:
      - ci/cd
  pull_request:
    branches:
      - ci/cd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose    

      - name: Print environment variables
        run: |
          echo "APP_PORT=${{ secrets.APP_PORT }}"
          echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}"

      - name: Build Docker images
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: watchlist-app:latest

      - name: Run Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d

      - name: Run tests
        run: |
          # Замените на команду для запуска тестов
          docker-compose exec -T app go test ./...

      - name: Shutdown Docker Compose
        run: |
          docker-compose down
