name: CI Watchlist

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - ${{ secrets.POSTGRES_PORT }}:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Newman
        run: npm install -g newman

      - name: Build and run Docker Compose
        run: |
          docker-compose up --build -d
          sleep 10
        env:
          APP_PORT: ${{ secrets.APP_PORT }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}

      - name: Run Postman tests with Newman
        run: |
          newman run tests/postman_collection.json -e tests/postman_environment.json
        env:
          APP_HOST: ${{ secrets.APP_HOST }}
          APP_PORT: ${{ secrets.APP_PORT }}

      - name: Stop and clean up
        run: docker-compose down --volumes
